public class OnlineCoursePageCloneController {
	public string location {get;set;}
    public string category {get;set;}
    public string level {get;set;}
    public string type {get;set;}
    
    public OnlineCoursePageCloneController(){}
    
    public List<SelectOption> getLocationList(){
        List<SelectOption> locationOptList = new List<SelectOption>();
        for(Account acc : [SELECT Id,Name FROM Account WHERE RecordType.Name = 'Location']){
            locationOptList.add(new SelectOption(acc.Id,acc.Name));
        } 
        
        return locationOptList;
    }
    
    public List<SelectOption> getCategoryList(){
        List<SelectOption> listCategory = new List<SelectOption>();
        for(String catValue : UtilityClass.getPickValues('educato__Course__c','educato__Category__c')){
            listCategory.add(new SelectOption(catValue,catValue));
        } 
        
        return listCategory;
    }
    
    public List<SelectOption> getLevelList(){
        List<SelectOption> levelOptList = new List<SelectOption>();
        for(String catValue : UtilityClass.getPickValues('educato__Course__c','educato__Level__c')){
            levelOptList.add(new SelectOption(catValue,catValue));
        } 
        
        return levelOptList;
    }
    
    public List<SelectOption> getTypeList(){
        List<SelectOption> typeOptList = new List<SelectOption>();
        for(String catValue : UtilityClass.getPickValues('educato__Course__c','educato__Type__c')){
            typeOptList.add(new SelectOption(catValue,catValue));
        } 
        
        return typeOptList;
    }
 }