public class SearchCourseCmpController {
	public string locationStr;
    Public string categoryString;
    Public string levelString;
    Public string typeString;

    //string tempLocStr;
    public SearchCourseCmpController(){
        searchCourses();
    }
    
    public id getlocationStr(){return locationStr;}     
    public void setlocationStr(String s){
        if (s!=locationStr){
          locationStr = s;
          searchCourses();
        }
   }
    
    public id getcategoryString(){return categoryString;}     
    public void setcategoryString(String s){
        if (s!=categoryString){
            categoryString = s;
            searchCourses();
        }
    } 
    
    public id getlevelString(){return levelString;}     
    public void setlevelString(String s){
        if (s!=levelString){
            levelString = s;
           searchCourses();
        }
    }
    
    public id gettypeString(){return typeString;}     
    public void settypeString(String s){
        if (s!=typeString){
          typeString = s;
          searchCourses();
        }
   }
    
    public void searchCourses(){
        System.debug('@@@@'+locationStr);
        System.debug('@@@@'+categoryString);
        System.debug('@@@@'+levelString);
        System.debug('@@@@'+typeString);
    }
   
}