/*
	Name		:	VirtualClassParser
	Date		:	03/05/2020
	Author		:	Arpit vijayvergiya
	Description	:	This is common class which return the key values after virtual class creation through meeting.

*/
public class VirtualClassParser {
	public long meetingId;
    public String meetingStartUrl;
    public String joinUrl;
    public String hostId;
    public String topic;
    public String agenda;
    public Integer meetingType; 
    public List<VirtualClassOccurence> occurrences;
}